# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test (Node.js ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Upload coverage
        if: ${{ github.event_name != 'pull_request' }}
        run: yarn coverage
